In [1]:
import seaborn as sns 
# apply seaborn library in sns 

In [2]:
data=sns.load_dataset("car_crashes")
# data taken from seaborn library 

In [3]:
data

total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
0    18.8     7.332    5.640          18.048       15.040       784.55   
1    18.1     7.421    4.525          16.290       17.014      1053.48   
2    18.6     6.510    5.208          15.624       17.856       899.47   
3    22.4     4.032    5.824          21.056       21.280       827.34   
4    12.0     4.200    3.360          10.920       10.680       878.41   
5    13.6     5.032    3.808          10.744       12.920       835.50   
6    10.8     4.968    3.888           9.396        8.856      1068.73   
7    16.2     6.156    4.860          14.094       16.038      1137.87   
8     5.9     2.006    1.593           5.900        5.900      1273.89   
9    17.9     3.759    5.191          16.468       16.826      1160.13   
10   15.6     2.964    3.900          14.820       14.508       913.15   
11   17.5     9.450    7.175          14.350       15.225       861.18   
12   15.3     5.508    4.437          13.005       14.994       641.96   
13   12.8     4.608    4.352          12.032       12.288       803.11   
14   14.5     3.625    4.205          13.775       13.775       710.46   
15   15.7     2.669    3.925          15.229       13.659       649.06   
16   17.8     4.806    4.272          13.706       15.130       780.45   
17   21.4     4.066    4.922          16.692       16.264       872.51   
18   20.5     7.175    6.765          14.965       20.090      1281.55   
19   15.1     5.738    4.530          13.137       12.684       661.88   
20   12.5     4.250    4.000           8.875       12.375      1048.78   
21    8.2     1.886    2.870           7.134        6.560      1011.14   
22   14.1     3.384    3.948          13.395       10.857      1110.61   
23    9.6     2.208    2.784           8.448        8.448       777.18   
24   17.6     2.640    5.456           1.760       17.600       896.07   
25   16.1     6.923    5.474          14.812       13.524       790.32   
26   21.4     8.346    9.416          17.976       18.190       816.21   
27   14.9     1.937    5.215          13.857       13.410       732.28   
28   14.7     5.439    4.704          13.965       14.553      1029.87   
29   11.6     4.060    3.480          10.092        9.628       746.54   
30   11.2     1.792    3.136           9.632        8.736      1301.52   
31   18.4     3.496    4.968          12.328       18.032       869.85   
32   12.3     3.936    3.567          10.824        9.840      1234.31   
33   16.8     6.552    5.208          15.792       13.608       708.24   
34   23.9     5.497   10.038          23.661       20.554       688.75   
35   14.1     3.948    4.794          13.959       11.562       697.73   
36   19.9     6.368    5.771          18.308       18.706       881.51   
37   12.8     4.224    3.328           8.576       11.520       804.71   
38   18.2     9.100    5.642          17.472       16.016       905.99   
39   11.1     3.774    4.218          10.212        8.769      1148.99   
40   23.9     9.082    9.799          22.944       19.359       858.97   
41   19.4     6.014    6.402          19.012       16.684       669.31   
42   19.5     4.095    5.655          15.990       15.795       767.91   
43   19.4     7.760    7.372          17.654       16.878      1004.75   
44   11.3     4.859    1.808           9.944       10.848       809.38   
45   13.6     4.080    4.080          13.056       12.920       716.20   
46   12.7     2.413    3.429          11.049       11.176       768.95   
47   10.6     4.452    3.498           8.692        9.116       890.03   
48   23.8     8.092    6.664          23.086       20.706       992.61   
49   13.8     4.968    4.554           5.382       11.592       670.31   
50   17.4     7.308    5.568          14.094       15.660       791.14   

    ins_losses abbrev  
0       145.08     AL  
1       133.93     AK  
2       110.35     AZ  
3       142.39     AR  
4       165.63     CA  
5       139

In [5]:
data.to_csv("car_crashes.csv",index=False)
data.to_csv("car_crashes.xlsx",index=False)
# for saving data 

In [7]:
import pandas as pd
# apply pandas library in pd 

In [8]:
data=pd.read_csv("car_crashes.csv")

In [9]:
data

total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
0    18.8     7.332    5.640          18.048       15.040       784.55   
1    18.1     7.421    4.525          16.290       17.014      1053.48   
2    18.6     6.510    5.208          15.624       17.856       899.47   
3    22.4     4.032    5.824          21.056       21.280       827.34   
4    12.0     4.200    3.360          10.920       10.680       878.41   
5    13.6     5.032    3.808          10.744       12.920       835.50   
6    10.8     4.968    3.888           9.396        8.856      1068.73   
7    16.2     6.156    4.860          14.094       16.038      1137.87   
8     5.9     2.006    1.593           5.900        5.900      1273.89   
9    17.9     3.759    5.191          16.468       16.826      1160.13   
10   15.6     2.964    3.900          14.820       14.508       913.15   
11   17.5     9.450    7.175          14.350       15.225       861.18   
12   15.3     5.508    4.437          13.005       14.994       641.96   
13   12.8     4.608    4.352          12.032       12.288       803.11   
14   14.5     3.625    4.205          13.775       13.775       710.46   
15   15.7     2.669    3.925          15.229       13.659       649.06   
16   17.8     4.806    4.272          13.706       15.130       780.45   
17   21.4     4.066    4.922          16.692       16.264       872.51   
18   20.5     7.175    6.765          14.965       20.090      1281.55   
19   15.1     5.738    4.530          13.137       12.684       661.88   
20   12.5     4.250    4.000           8.875       12.375      1048.78   
21    8.2     1.886    2.870           7.134        6.560      1011.14   
22   14.1     3.384    3.948          13.395       10.857      1110.61   
23    9.6     2.208    2.784           8.448        8.448       777.18   
24   17.6     2.640    5.456           1.760       17.600       896.07   
25   16.1     6.923    5.474          14.812       13.524       790.32   
26   21.4     8.346    9.416          17.976       18.190       816.21   
27   14.9     1.937    5.215          13.857       13.410       732.28   
28   14.7     5.439    4.704          13.965       14.553      1029.87   
29   11.6     4.060    3.480          10.092        9.628       746.54   
30   11.2     1.792    3.136           9.632        8.736      1301.52   
31   18.4     3.496    4.968          12.328       18.032       869.85   
32   12.3     3.936    3.567          10.824        9.840      1234.31   
33   16.8     6.552    5.208          15.792       13.608       708.24   
34   23.9     5.497   10.038          23.661       20.554       688.75   
35   14.1     3.948    4.794          13.959       11.562       697.73   
36   19.9     6.368    5.771          18.308       18.706       881.51   
37   12.8     4.224    3.328           8.576       11.520       804.71   
38   18.2     9.100    5.642          17.472       16.016       905.99   
39   11.1     3.774    4.218          10.212        8.769      1148.99   
40   23.9     9.082    9.799          22.944       19.359       858.97   
41   19.4     6.014    6.402          19.012       16.684       669.31   
42   19.5     4.095    5.655          15.990       15.795       767.91   
43   19.4     7.760    7.372          17.654       16.878      1004.75   
44   11.3     4.859    1.808           9.944       10.848       809.38   
45   13.6     4.080    4.080          13.056       12.920       716.20   
46   12.7     2.413    3.429          11.049       11.176       768.95   
47   10.6     4.452    3.498           8.692        9.116       890.03   
48   23.8     8.092    6.664          23.086       20.706       992.61   
49   13.8     4.968    4.554           5.382       11.592       670.31   
50   17.4     7.308    5.568          14.094       15.660       791.14   

    ins_losses abbrev  
0       145.08     AL  
1       133.93     AK  
2       110.35     AZ  
3       142.39     AR  
4       165.63     CA  
5       139

In [10]:
data.shape

(51, 8)

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   total           51 non-null     float64
 1   speeding        51 non-null     float64
 2   alcohol         51 non-null     float64
 3   not_distracted  51 non-null     float64
 4   no_previous     51 non-null     float64
 5   ins_premium     51 non-null     float64
 6   ins_losses      51 non-null     float64
 7   abbrev          51 non-null     object 
dtypes: float64(7), object(1)
memory usage: 3.3+ KB


In [12]:
data.describe()

total   speeding    alcohol  not_distracted  no_previous  \
count  51.000000  51.000000  51.000000       51.000000    51.000000   
mean   15.790196   4.998196   4.886784       13.573176    14.004882   
std     4.122002   2.017747   1.729133        4.508977     3.764672   
min     5.900000   1.792000   1.593000        1.760000     5.900000   
25%    12.750000   3.766500   3.894000       10.478000    11.348000   
50%    15.600000   4.608000   4.554000       13.857000    13.775000   
75%    18.500000   6.439000   5.604000       16.140000    16.755000   
max    23.900000   9.450000  10.038000       23.661000    21.280000   

       ins_premium  ins_losses  
count    51.000000   51.000000  
mean    886.957647  134.493137  
std     178.296285   24.835922  
min     641.960000   82.750000  
25%     768.430000  114.645000  
50%     858.970000  136.050000  
75%    1007.945000  151.870000  
max    1301.520000  194.780000

In [13]:
data.describe(include="all")

total   speeding    alcohol  not_distracted  no_previous  \
count   51.000000  51.000000  51.000000       51.000000    51.000000   
unique        NaN        NaN        NaN             NaN          NaN   
top           NaN        NaN        NaN             NaN          NaN   
freq          NaN        NaN        NaN             NaN          NaN   
mean    15.790196   4.998196   4.886784       13.573176    14.004882   
std      4.122002   2.017747   1.729133        4.508977     3.764672   
min      5.900000   1.792000   1.593000        1.760000     5.900000   
25%     12.750000   3.766500   3.894000       10.478000    11.348000   
50%     15.600000   4.608000   4.554000       13.857000    13.775000   
75%     18.500000   6.439000   5.604000       16.140000    16.755000   
max     23.900000   9.450000  10.038000       23.661000    21.280000   

        ins_premium  ins_losses abbrev  
count     51.000000   51.000000     51  
unique          NaN         NaN     51  
top             NaN         NaN     AL  
freq            NaN         NaN      1  
mean     886.957647  134.493137    NaN  
std      178.296285   24.835922    NaN  
min      641.960000   82.750000    NaN  
25%      768.430000  114.645000    NaN  
50%      858.970000  136.050000    NaN  
75%     1007.945000  151.870000    NaN  
max     1301.520000  194.780000    NaN

In [14]:
data.head()

total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
0   18.8     7.332    5.640          18.048       15.040       784.55   
1   18.1     7.421    4.525          16.290       17.014      1053.48   
2   18.6     6.510    5.208          15.624       17.856       899.47   
3   22.4     4.032    5.824          21.056       21.280       827.34   
4   12.0     4.200    3.360          10.920       10.680       878.41   

   ins_losses abbrev  
0      145.08     AL  
1      133.93     AK  
2      110.35     AZ  
3      142.39     AR  
4      165.63     CA

In [15]:
data.head(2)

total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
0   18.8     7.332    5.640          18.048       15.040       784.55   
1   18.1     7.421    4.525          16.290       17.014      1053.48   

   ins_losses abbrev  
0      145.08     AL  
1      133.93     AK

In [16]:
data.tail()

total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
46   12.7     2.413    3.429          11.049       11.176       768.95   
47   10.6     4.452    3.498           8.692        9.116       890.03   
48   23.8     8.092    6.664          23.086       20.706       992.61   
49   13.8     4.968    4.554           5.382       11.592       670.31   
50   17.4     7.308    5.568          14.094       15.660       791.14   

    ins_losses abbrev  
46      153.72     VA  
47      111.62     WA  
48      152.56     WV  
49      106.62     WI  
50      122.04     WY

In [17]:
data.tail(10)

total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
41   19.4     6.014    6.402          19.012       16.684       669.31   
42   19.5     4.095    5.655          15.990       15.795       767.91   
43   19.4     7.760    7.372          17.654       16.878      1004.75   
44   11.3     4.859    1.808           9.944       10.848       809.38   
45   13.6     4.080    4.080          13.056       12.920       716.20   
46   12.7     2.413    3.429          11.049       11.176       768.95   
47   10.6     4.452    3.498           8.692        9.116       890.03   
48   23.8     8.092    6.664          23.086       20.706       992.61   
49   13.8     4.968    4.554           5.382       11.592       670.31   
50   17.4     7.308    5.568          14.094       15.660       791.14   

    ins_losses abbrev  
41       96.87     SD  
42      155.57     TN  
43      156.83     TX  
44      109.48     UT  
45      109.61     VT  
46      153.72     VA  
47      111.62     WA  
48      152.56     WV  
49      106.62     WI  
50      122.04     WY

In [18]:
data.columns

Index(['total', 'speeding', 'alcohol', 'not_distracted', 'no_previous',
       'ins_premium', 'ins_losses', 'abbrev'],
      dtype='object')

In [22]:
data["speeding"]

0     7.332
1     7.421
2     6.510
3     4.032
4     4.200
5     5.032
6     4.968
7     6.156
8     2.006
9     3.759
10    2.964
11    9.450
12    5.508
13    4.608
14    3.625
15    2.669
16    4.806
17    4.066
18    7.175
19    5.738
20    4.250
21    1.886
22    3.384
23    2.208
24    2.640
25    6.923
26    8.346
27    1.937
28    5.439
29    4.060
30    1.792
31    3.496
32    3.936
33    6.552
34    5.497
35    3.948
36    6.368
37    4.224
38    9.100
39    3.774
40    9.082
41    6.014
42    4.095
43    7.760
44    4.859
45    4.080
46    2.413
47    4.452
48    8.092
49    4.968
50    7.308
Name: speeding, dtype: float64

In [24]:
data[["speeding","alcohol"]]

speeding  alcohol
0      7.332    5.640
1      7.421    4.525
2      6.510    5.208
3      4.032    5.824
4      4.200    3.360
5      5.032    3.808
6      4.968    3.888
7      6.156    4.860
8      2.006    1.593
9      3.759    5.191
10     2.964    3.900
11     9.450    7.175
12     5.508    4.437
13     4.608    4.352
14     3.625    4.205
15     2.669    3.925
16     4.806    4.272
17     4.066    4.922
18     7.175    6.765
19     5.738    4.530
20     4.250    4.000
21     1.886    2.870
22     3.384    3.948
23     2.208    2.784
24     2.640    5.456
25     6.923    5.474
26     8.346    9.416
27     1.937    5.215
28     5.439    4.704
29     4.060    3.480
30     1.792    3.136
31     3.496    4.968
32     3.936    3.567
33     6.552    5.208
34     5.497   10.038
35     3.948    4.794
36     6.368    5.771
37     4.224    3.328
38     9.100    5.642
39     3.774    4.218
40     9.082    9.799
41     6.014    6.402
42     4.095    5.655
43     7.760    7.372
44     4.859    1.808
45     4.080    4.080
46     2.413    3.429
47     4.452    3.498
48     8.092    6.664
49     4.968    4.554
50     7.308    5.568

In [25]:
data.set_index("speeding")

total  alcohol  not_distracted  no_previous  ins_premium  \
speeding                                                             
7.332      18.8    5.640          18.048       15.040       784.55   
7.421      18.1    4.525          16.290       17.014      1053.48   
6.510      18.6    5.208          15.624       17.856       899.47   
4.032      22.4    5.824          21.056       21.280       827.34   
4.200      12.0    3.360          10.920       10.680       878.41   
5.032      13.6    3.808          10.744       12.920       835.50   
4.968      10.8    3.888           9.396        8.856      1068.73   
6.156      16.2    4.860          14.094       16.038      1137.87   
2.006       5.9    1.593           5.900        5.900      1273.89   
3.759      17.9    5.191          16.468       16.826      1160.13   
2.964      15.6    3.900          14.820       14.508       913.15   
9.450      17.5    7.175          14.350       15.225       861.18   
5.508      15.3    4.437          13.005       14.994       641.96   
4.608      12.8    4.352          12.032       12.288       803.11   
3.625      14.5    4.205          13.775       13.775       710.46   
2.669      15.7    3.925          15.229       13.659       649.06   
4.806      17.8    4.272          13.706       15.130       780.45   
4.066      21.4    4.922          16.692       16.264       872.51   
7.175      20.5    6.765          14.965       20.090      1281.55   
5.738      15.1    4.530          13.137       12.684       661.88   
4.250      12.5    4.000           8.875       12.375      1048.78   
1.886       8.2    2.870           7.134        6.560      1011.14   
3.384      14.1    3.948          13.395       10.857      1110.61   
2.208       9.6    2.784           8.448        8.448       777.18   
2.640      17.6    5.456           1.760       17.600       896.07   
6.923      16.1    5.474          14.812       13.524       790.32   
8.346      21.4    9.416          17.976       18.190       816.21   
1.937      14.9    5.215          13.857       13.410       732.28   
5.439      14.7    4.704          13.965       14.553      1029.87   
4.060      11.6    3.480          10.092        9.628       746.54   
1.792      11.2    3.136           9.632        8.736      1301.52   
3.496      18.4    4.968          12.328       18.032       869.85   
3.936      12.3    3.567          10.824        9.840      1234.31   
6.552      16.8    5.208          15.792       13.608       708.24   
5.497      23.9   10.038          23.661       20.554       688.75   
3.948      14.1    4.794          13.959       11.562       697.73   
6.368      19.9    5.771          18.308       18.706       881.51   
4.224      12.8    3.328           8.576       11.520       804.71   
9.100      18.2    5.642          17.472       16.016       905.99   
3.774      11.1    4.218          10.212        8.769      1148.99   
9.082      23.9    9.799          22.944       19.359       858.97   
6.014      19.4    6.402          19.012       16.684       669.31   
4.095      19.5    5.655          15.990       15.795       767.91   
7.760      19.4    7.372          17.654       16.878      1004.75   
4.859      11.3    1.808           9.944       10.848       809.38   
4.080      13.6    4.080          13.056       12.920       716.20   
2.413      12.7    3.429          11.049       11.176       768.95   
4.452      10.6    3.498           8.692        9.116       890.03   
8.092      23.8    6.664          23.086       20.706       992.61   
4.968      13.8    4.554           5.382       11.592       670.31   
7.308      17.4    5.568          14.094       15.660       791.14   

          ins_losses abbrev  
speeding                     
7.332         145.08     AL  
7.421         133.93     AK  
6.510         110.35     AZ  
4.032         142.39     AR  
4.200         165.63     CA  
5.032         139.91     CO  
4.968         167.02     CT  
6.156         151.48     DE  

In [26]:
type(data)

pandas.core.frame.DataFrame

In [27]:
type(data[["speeding","alcohol"]])

pandas.core.frame.DataFrame

In [28]:
type(data["alcohol"])

pandas.core.series.Series

In [30]:
data.columns

Index(['total', 'speeding', 'alcohol', 'not_distracted', 'no_previous',
       'ins_premium', 'ins_losses', 'abbrev'],
      dtype='object')

In [31]:
data["alcohol"].unique()

array([ 5.64 ,  4.525,  5.208,  5.824,  3.36 ,  3.808,  3.888,  4.86 ,
        1.593,  5.191,  3.9  ,  7.175,  4.437,  4.352,  4.205,  3.925,
        4.272,  4.922,  6.765,  4.53 ,  4.   ,  2.87 ,  3.948,  2.784,
        5.456,  5.474,  9.416,  5.215,  4.704,  3.48 ,  3.136,  4.968,
        3.567, 10.038,  4.794,  5.771,  3.328,  5.642,  4.218,  9.799,
        6.402,  5.655,  7.372,  1.808,  4.08 ,  3.429,  3.498,  6.664,
        4.554,  5.568])

In [32]:
data["alcohol"].value_counts()

alcohol
5.208     2
5.640     1
4.525     1
5.824     1
3.360     1
3.808     1
3.888     1
4.860     1
1.593     1
5.191     1
3.900     1
7.175     1
4.437     1
4.352     1
4.205     1
3.925     1
4.272     1
4.922     1
6.765     1
4.530     1
4.000     1
2.870     1
3.948     1
2.784     1
5.456     1
5.474     1
9.416     1
5.215     1
4.704     1
3.480     1
3.136     1
4.968     1
3.567     1
10.038    1
4.794     1
5.771     1
3.328     1
5.642     1
4.218     1
9.799     1
6.402     1
5.655     1
7.372     1
1.808     1
4.080     1
3.429     1
3.498     1
6.664     1
4.554     1
5.568     1
Name: count, dtype: int64

In [33]:
data.isnull()

total  speeding  alcohol  not_distracted  no_previous  ins_premium  \
0   False     False    False           False        False        False   
1   False     False    False           False        False        False   
2   False     False    False           False        False        False   
3   False     False    False           False        False        False   
4   False     False    False           False        False        False   
5   False     False    False           False        False        False   
6   False     False    False           False        False        False   
7   False     False    False           False        False        False   
8   False     False    False           False        False        False   
9   False     False    False           False        False        False   
10  False     False    False           False        False        False   
11  False     False    False           False        False        False   
12  False     False    False           False        False        False   
13  False     False    False           False        False        False   
14  False     False    False           False        False        False   
15  False     False    False           False        False        False   
16  False     False    False           False        False        False   
17  False     False    False           False        False        False   
18  False     False    False           False        False        False   
19  False     False    False           False        False        False   
20  False     False    False           False        False        False   
21  False     False    False           False        False        False   
22  False     False    False           False        False        False   
23  False     False    False           False        False        False   
24  False     False    False           False        False        False   
25  False     False    False           False        False        False   
26  False     False    False           False        False        False   
27  False     False    False           False        False        False   
28  False     False    False           False        False        False   
29  False     False    False           False        False        False   
30  False     False    False           False        False        False   
31  False     False    False           False        False        False   
32  False     False    False           False        False        False   
33  False     False    False           False        False        False   
34  False     False    False           False        False        False   
35  False     False    False           False        False        False   
36  False     False    False           False        False        False   
37  False     False    False           False        False        False   
38  False     False    False           False        False        False   
39  False     False    False           False        False        False   
40  False     False    False           False        False        False   
41  False     False    False           False        False        False   
42  False     False    False           False        False        False   
43  False     False    False           False        False        False   
44  False     False    False           False        False        False   
45  False     False    False           False        False        False   
46  False     False    False           False        False        False   
47  False     False    False           False        False        False   
48  False     False    False           False        False        False   
49  False     False    False           False        False        False   
50  False     False    False           False        False        False   

    ins_losses  abbrev  
0        False   False  
1        False   False  
2        False   False  
3        False   False  
4        False   False  
5    

In [34]:
data.isnull().sum()

total             0
speeding          0
alcohol           0
not_distracted    0
no_previous       0
ins_premium       0
ins_losses        0
abbrev            0
dtype: int64

In [35]:
data.isnull().sum().sum()

np.int64(0)

In [42]:
df=sns.load_dataset('titanic')

In [43]:
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]

In [44]:
df.shape

(891, 15)

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [46]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [47]:
df.describe()

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [49]:
df.describe(include="all")

survived      pclass   sex         age       sibsp       parch  \
count   891.000000  891.000000   891  714.000000  891.000000  891.000000   
unique         NaN         NaN     2         NaN         NaN         NaN   
top            NaN         NaN  male         NaN         NaN         NaN   
freq           NaN         NaN   577         NaN         NaN         NaN   
mean      0.383838    2.308642   NaN   29.699118    0.523008    0.381594   
std       0.486592    0.836071   NaN   14.526497    1.102743    0.806057   
min       0.000000    1.000000   NaN    0.420000    0.000000    0.000000   
25%       0.000000    2.000000   NaN   20.125000    0.000000    0.000000   
50%       0.000000    3.000000   NaN   28.000000    0.000000    0.000000   
75%       1.000000    3.000000   NaN   38.000000    1.000000    0.000000   
max       1.000000    3.000000   NaN   80.000000    8.000000    6.000000   

              fare embarked  class  who adult_male deck  embark_town alive  \
count   891.000000      889    891  891        891  203          889   891   
unique         NaN        3      3    3          2    7            3     2   
top            NaN        S  Third  man       True    C  Southampton    no   
freq           NaN      644    491  537        537   59          644   549   
mean     32.204208      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
std      49.693429      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
min       0.000000      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
25%       7.910400      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
50%      14.454200      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
75%      31.000000      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
max     512.329200      NaN    NaN  NaN        NaN  NaN          NaN   NaN   

       alone  
count    891  
unique     2  
top     True  
freq     537  
mean     NaN  
std      NaN  
min      NaN  
25%      NaN  
50%      NaN  
75%      NaN  
max      NaN

In [50]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [51]:
df.head(10)

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0         0       3    male  22.0      1      0   7.2500        S   Third   
1         1       1  female  38.0      1      0  71.2833        C   First   
2         1       3  female  26.0      0      0   7.9250        S   Third   
3         1       1  female  35.0      1      0  53.1000        S   First   
4         0       3    male  35.0      0      0   8.0500        S   Third   
5         0       3    male   NaN      0      0   8.4583        Q   Third   
6         0       1    male  54.0      0      0  51.8625        S   First   
7         0       3    male   2.0      3      1  21.0750        S   Third   
8         1       3  female  27.0      0      2  11.1333        S   Third   
9         1       2  female  14.0      1      0  30.0708        C  Second   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  
5    man        True  NaN   Queenstown    no   True  
6    man        True    E  Southampton    no   True  
7  child       False  NaN  Southampton    no  False  
8  woman       False  NaN  Southampton   yes  False  
9  child       False  NaN    Cherbourg   yes  False

In [52]:
df.tail()

survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
886         0       2    male  27.0      0      0  13.00        S  Second   
887         1       1  female  19.0      0      0  30.00        S   First   
888         0       3  female   NaN      1      2  23.45        S   Third   
889         1       1    male  26.0      0      0  30.00        C   First   
890         0       3    male  32.0      0      0   7.75        Q   Third   

       who  adult_male deck  embark_town alive  alone  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True

In [53]:
df.tail(20)

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
871         1       1  female  47.0      1      1  52.5542        S   First   
872         0       1    male  33.0      0      0   5.0000        S   First   
873         0       3    male  47.0      0      0   9.0000        S   Third   
874         1       2  female  28.0      1      0  24.0000        C  Second   
875         1       3  female  15.0      0      0   7.2250        C   Third   
876         0       3    male  20.0      0      0   9.8458        S   Third   
877         0       3    male  19.0      0      0   7.8958        S   Third   
878         0       3    male   NaN      0      0   7.8958        S   Third   
879         1       1  female  56.0      0      1  83.1583        C   First   
880         1       2  female  25.0      0      1  26.0000        S  Second   
881         0       3    male  33.0      0      0   7.8958        S   Third   
882         0       3  female  22.0      0      0  10.5167        S   Third   
883         0       2    male  28.0      0      0  10.5000        S  Second   
884         0       3    male  25.0      0      0   7.0500        S   Third   
885         0       3  female  39.0      0      5  29.1250        Q   Third   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
871  woman       False    D  Southampton   yes  False  
872    man        True    B  Southampton    no   True  
873    man        True  NaN  Southampton    no   True  
874  woman       False  NaN    Cherbourg   yes  False  
875  child       False  NaN    Cherbourg   yes   True  
876    man        True  NaN  Southampton    no   True  
877    man        True  NaN  Southampton    no   True  
878    man        True  NaN  Southampton    no   True  
879  woman       False    C    Cherbourg   yes  False  
880  woman       False  NaN  Southampton   yes  False  
881    man        True  NaN  Southampton    no   True  
882  woman       False  NaN  Southampton    no   True  
883    man        True  NaN  Southampton    no   True  
884    man        True  NaN  Southampton    no   True  
885  woman       False  NaN   Queenstown    no  False  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True

In [54]:
df.set_index("age")

survived  pclass     sex  sibsp  parch     fare embarked   class    who  \
age                                                                             
22.0         0       3    male      1      0   7.2500        S   Third    man   
38.0         1       1  female      1      0  71.2833        C   First  woman   
26.0         1       3  female      0      0   7.9250        S   Third  woman   
35.0         1       1  female      1      0  53.1000        S   First  woman   
35.0         0       3    male      0      0   8.0500        S   Third    man   
...        ...     ...     ...    ...    ...      ...      ...     ...    ...   
27.0         0       2    male      0      0  13.0000        S  Second    man   
19.0         1       1  female      0      0  30.0000        S   First  woman   
NaN          0       3  female      1      2  23.4500        S   Third  woman   
26.0         1       1    male      0      0  30.0000        C   First    man   
32.0         0       3    male      0      0   7.7500        Q   Third    man   

      adult_male deck  embark_town alive  alone  
age                                              
22.0        True  NaN  Southampton    no  False  
38.0       False    C    Cherbourg   yes  False  
26.0       False  NaN  Southampton   yes   True  
35.0       False    C  Southampton   yes  False  
35.0        True  NaN  Southampton    no   True  
...          ...  ...          ...   ...    ...  
27.0        True  NaN  Southampton    no   True  
19.0       False    B  Southampton   yes   True  
NaN        False  NaN  Southampton    no  False  
26.0        True    C    Cherbourg   yes   True  
32.0        True  NaN   Queenstown    no   True  

[891 rows x 14 columns]

In [55]:
df["age"]

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: age, Length: 891, dtype: float64

In [56]:
df[["age","who"]]

age    who
0    22.0    man
1    38.0  woman
2    26.0  woman
3    35.0  woman
4    35.0    man
..    ...    ...
886  27.0    man
887  19.0  woman
888   NaN  woman
889  26.0    man
890  32.0    man

[891 rows x 2 columns]

In [57]:
type(df)

pandas.core.frame.DataFrame

In [58]:
type(df[["age","who"]])

pandas.core.frame.DataFrame

In [59]:
type(df["age"])

pandas.core.series.Series

In [60]:
df["who"].unique()

array(['man', 'woman', 'child'], dtype=object)

In [61]:
df["who"].value_counts()

who
man      537
woman    271
child     83
Name: count, dtype: int64

In [62]:
df.isnull()

survived  pclass    sex    age  sibsp  parch   fare  embarked  class  \
0       False   False  False  False  False  False  False     False  False   
1       False   False  False  False  False  False  False     False  False   
2       False   False  False  False  False  False  False     False  False   
3       False   False  False  False  False  False  False     False  False   
4       False   False  False  False  False  False  False     False  False   
..        ...     ...    ...    ...    ...    ...    ...       ...    ...   
886     False   False  False  False  False  False  False     False  False   
887     False   False  False  False  False  False  False     False  False   
888     False   False  False   True  False  False  False     False  False   
889     False   False  False  False  False  False  False     False  False   
890     False   False  False  False  False  False  False     False  False   

       who  adult_male   deck  embark_town  alive  alone  
0    False       False   True        False  False  False  
1    False       False  False        False  False  False  
2    False       False   True        False  False  False  
3    False       False  False        False  False  False  
4    False       False   True        False  False  False  
..     ...         ...    ...          ...    ...    ...  
886  False       False   True        False  False  False  
887  False       False  False        False  False  False  
888  False       False   True        False  False  False  
889  False       False  False        False  False  False  
890  False       False   True        False  False  False  

[891 rows x 15 columns]

In [63]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [64]:
df.isnull().sum().sum()

np.int64(869)

In [65]:
df["age"]=df["age"].fillna(df["age"].mean())
# it is use for fill missing values and only use on numerical values 


In [66]:
df["age"]=df["age"].fillna(df["age"].median())
# it is use for filling missing values and only use in numerical and outlier 

In [67]:
df["deck"]=df["deck"].fillna(df["deck"].mode()[0])
# it is use for filling missing values in category and string 

In [68]:
import numpy as np

In [69]:
l=[1,2,3,4]
arr=np.array(l)
arr

array([1, 2, 3, 4])

In [70]:
s="LPU IBM Kabir UNIversity "
arr2=np.array(s)
arr2

array('LPU IBM Kabir UNIversity ', dtype='<U25')

In [71]:
arr3=np.array(["S",567,True,"kjhgf"])
arr3

array(['S', '567', 'True', 'kjhgf'], dtype='<U21')

In [72]:
arr4=np.arange(11,dtype="float") # syn 1
arr4

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [73]:
arr5=np.arange(10,21) # syn 2
arr5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [74]:
arr6=np.arange(10,21,2) # syn 3
arr6

array([10, 12, 14, 16, 18, 20])

In [75]:
arr7=np.zeros(7)
arr7

array([0., 0., 0., 0., 0., 0., 0.])

In [76]:
arr8=np.zeros((7,8))
arr8

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [77]:
arr9=np.ones(3)
arr9

array([1., 1., 1.])

In [78]:
arr10=np.ones((3,3))
arr10

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])